[project]
name = "smash-overlay-commander"
version = "0.1.5"
description = "App to control OBS Tournament Overlay"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Holy Knife", email = "provostdevin@gmail.com" }
]
dependencies = [
    "flet>=0.80.5",
    "obs-websocket-py>=1.0"
]

[dependency-groups]
dev = [
    "flet-cli>=0.80.5",
    "flet-desktop-light>=0.80.5",
    "flet-web>=0.80.5",
    "obs-websocket-py>=1.0",
    ""
]

[tool.flet]
org = "com.mycompany"
product = "smash-overlay-commander"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"

[tool.flet.app]
path = "src"
